name: YOCaml deploy documentation
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.x
          opam-depext-flags: --with-doc

      - run: opam install . --deps-only --with-doc
      - run: opam install preface
      - run: opam exec -- dune build
      - run: opam exec -- dune build @doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html/
          destination_dir: .
          enable_jekyll: false
